### ISSUE TITLE
did you open the file in text mode? 

### ISSUE THREAD

**Issue by pgeorgan** [drduh/macOS-Security-and-Privacy-Guide#259]
Traceback (most recent call last):
  File "read_launch_plists.py", line 107, in <module>
    main()
  File "read_launch_plists.py", line 93, in main
    comments = {rows[0]:rows[1] for rows in reader}
  File "read_launch_plists.py", line 93, in <dictcomp>
    comments = {rows[0]:rows[1] for rows in reader}
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

**Comment by pgeorgan** [comment]
Changed
`  with open(csvfile, 'rb') as f:
to
`  with open(csvfile, 'r') as f:

**Comment by pgeorgan** [comment]
New Issue:

`Traceback (most recent call last):
  File "read_launch_plists.py", line 107, in <module>
    main()
  File "read_launch_plists.py", line 98, in main
    p = LoadPlist(filename)
  File "read_launch_plists.py", line 31, in LoadPlist
    data = plistlib.readPlistFromString(out_data)
AttributeError: module 'plistlib' has no attribute 'readPlistFromString'
`

**Comment by drduh** [comment]
It's working for me. Please reopen with the version of Python you're using, if you still see this.

````
$ /usr/bin/python -V
Python 2.7.10
````

**Comment by pgeorgan** [comment]
Python 2.7.10

**Comment by typedefine** [comment]
How to deal with this issue in Python 3.9.0 ?
